server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/clients/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loans/**
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/kardex/**
        - id: rate-service
          uri: lb://rate-service
          predicates:
            - Path=/rate/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/report/**
        - id: tools-service
          uri: lb://tools-service
          predicates:
            - Path=/tools/**