server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka-service:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/toolrent
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/clients/**
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/api/loan/**
        - id: kardex-service
          uri: lb://kardex-service
          predicates:
            - Path=/api/kardex/**
        - id: rate-service
          uri: lb://rate-service
          predicates:
            - Path=/api/rates/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**
        - id: tools-service
          uri: lb://tools-service
          predicates:
            - Path=/api/tools/**,/api/general-tools/**